image: node:18

variables:
  PUBLIC_URL: "https://$CI_PROJECT_NAMESPACE.gitlab.io/$CI_PROJECT_NAME"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

pages:
  stage: deploy
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run build
    - mv build public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test:
  stage: test
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run build
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
